version: '3.9'
services:

  postgres:
    image: postgres
    container_name: checkin_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - checkin_volume:/var/lib/postgresql/data/

volumes:
  checkin_volume: