version: '3.9'
services:

  app:
    container_name: controle-de-ponto
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/checkin
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_HOST: checkin_postgres
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: checkin_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: checkin
    ports:
      - "5432:5432"
    volumes:
      - checkin_volume:/var/lib/postgresql/data/

volumes:
  checkin_volume: